import asyncio
import secrets

from sqlalchemy import select
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

from app.config import settings
from app.models.area import Area
from app.models.topic import Topic
from app.models.user import User
from app.models.user_area import UserArea
from app.utils.hashing import hash_password

SEED_EMAIL = "seed@60seconds.dev"

SEED_DATA = [
    {
        "name": "Computer Science",
        "topics": [
            "TCP/IP and how the internet routes data",
            "Memory management: stack vs heap",
            "Binary, bytes, and bitwise operations",
            "What happens when you type a URL",
            "How a database index works",
            "REST vs GraphQL explained simply",
            "Concurrency vs parallelism",
            "How the browser renders a page",
            "Public key cryptography in plain English",
            "Why garbage collection exists",
            "How hash tables achieve constant-time lookup",
            "Why Big O notation matters for real code",
            "What a compiler actually does",
            "The difference between compiled and interpreted languages",
            "How recursion actually works under the hood",
            "Why dynamic programming beats brute force",
            "What a race condition is",
            "How mutexes and locks prevent chaos",
            "The difference between processes and threads",
            "Why DNS is basically the internet's phonebook",
            "How HTTPS keeps your data private",
            "What a CDN actually does",
            "Why cache invalidation is famously hard",
            "How git actually tracks changes",
            "What a merge conflict really is",
            "Why linked lists still matter",
            "How binary search cuts problems in half",
            "What a trie is used for",
            "Why B-trees power most databases",
            "How virtual memory tricks your programs",
            "What a deadlock is and how to avoid one",
            "Why Big O isn't the whole story (constants matter)",
            "How TCP guarantees delivery (and UDP doesn't)",
            "What a load balancer actually decides",
            "Why idempotency matters in APIs",
            "How OAuth actually works",
            "What a race between coroutines looks like",
            "Why immutability simplifies concurrent code",
            "How JIT compilation speeds up interpreted code",
            "What a stack overflow actually is",
            "Why hash collisions are inevitable (and handled)",
            "How websockets differ from HTTP polling",
            "What a segmentation fault means",
            "Why Dijkstra's algorithm finds shortest paths",
            "How a Bloom filter saves memory",
            "What eventual consistency means",
            "Why null references are called a 'billion dollar mistake'",
            "How containers differ from virtual machines",
            "What makes a language 'Turing complete'",
            "Why P vs NP is still unsolved",
        ],
    },
    {
        "name": "System Design",
        "topics": [
            "CAP theorem",
            "Load balancing strategies",
            "Database sharding",
            "Caching layers (L1, L2, CDN)",
            "Message queues and async processing",
            "API rate limiting",
            "Event-driven architecture",
            "Monolith vs microservices tradeoffs",
            "Consistent hashing explained",
            "Why horizontal scaling beats vertical scaling",
            "What a single point of failure is",
            "How database replication keeps systems available",
            "Why eventual consistency is a tradeoff, not a flaw",
            "What idempotent APIs protect against",
            "How a circuit breaker prevents cascading failures",
            "Why read replicas speed up read-heavy systems",
            "What a leader election protocol does",
            "How the outbox pattern avoids dual writes",
            "Why write-ahead logs make databases durable",
            "What backpressure means in streaming systems",
            "How rate limiters use token buckets",
            "Why idempotency keys prevent duplicate charges",
            "What a service mesh actually solves",
            "How blue-green deployments reduce downtime",
            "Why canary releases catch bugs early",
            "What database denormalization trades away",
            "How a distributed lock actually works",
            "Why the two generals problem is unsolvable",
            "What quorum reads and writes guarantee",
            "How Kafka partitions enable parallelism",
            "Why exactly-once delivery is nearly impossible",
            "What a bulkhead pattern isolates",
            "How feature flags decouple deploy from release",
            "Why observability is more than logging",
            "What SLA, SLO, and SLI actually mean",
            "How database connection pooling prevents overload",
            "Why stateless services scale more easily",
            "What a thundering herd problem looks like",
            "How CDNs reduce latency globally",
            "Why multi-region systems trade consistency for availability",
            "What a saga pattern coordinates",
            "How graceful degradation keeps systems usable",
            "Why idempotent consumers matter in queues",
            "What vertical partitioning splits apart",
            "How zero-downtime migrations actually work",
            "Why chaos engineering finds hidden failures",
            "What a hot partition problem is",
            "How API gateways centralize cross-cutting concerns",
            "Why designing for failure beats hoping nothing fails",
            "What the CAP theorem doesn't tell you",
        ],
    },
    {
        "name": "Machine Learning",
        "topics": [
            "Gradient descent in plain English",
            "What embeddings are and why they matter",
            "The attention mechanism in transformers",
            "Overfitting vs underfitting",
            "Bias-variance tradeoff",
            "Few-shot learning overview",
            "How a neural network actually learns",
            "Precision vs recall — when each matters",
            "Why more data beats a better algorithm",
            "What a loss function actually measures",
            "Why regularization prevents overfitting",
            "How backpropagation computes gradients",
            "What a learning rate controls",
            "Why batch size affects training stability",
            "How decision trees make splits",
            "What a random forest improves on a single tree",
            "Why cross-validation gives an honest score",
            "How k-means clustering groups data",
            "What dimensionality reduction actually does",
            "Why PCA finds the 'important' directions",
            "How support vector machines find a boundary",
            "What ensemble learning combines",
            "Why boosting differs from bagging",
            "How a confusion matrix reveals model behavior",
            "What the ROC curve actually shows",
            "Why feature engineering still matters",
            "How data leakage silently ruins models",
            "What a validation set is really for",
            "Why class imbalance breaks naive accuracy",
            "How convolutional layers detect patterns",
            "What pooling layers actually discard",
            "Why dropout prevents co-adaptation",
            "How batch normalization stabilizes training",
            "What transfer learning reuses",
            "Why fine-tuning beats training from scratch",
            "How recurrent networks handle sequences",
            "What vanishing gradients actually break",
            "Why LSTMs fixed the vanishing gradient problem",
            "How reinforcement learning differs from supervised learning",
            "What a reward function shapes",
            "Why exploration vs exploitation is a core tradeoff",
            "How clustering differs from classification",
            "What an activation function actually does",
            "Why ReLU replaced sigmoid in most networks",
            "How model interpretability is measured",
            "What SHAP values actually explain",
            "Why data quality beats model complexity",
            "How synthetic data can help or hurt",
            "What model drift means in production",
            "Why A/B testing models matters as much as offline metrics",
        ],
    },
    {
        "name": "Artificial Intelligence",
        "topics": [
            "How large language models generate text",
            "Reinforcement learning from human feedback (RLHF)",
            "Why hallucinations happen in LLMs",
            "The alignment problem explained simply",
            "AI agents: what they are and how they work",
            "RAG: retrieval-augmented generation",
            "Why context window size matters",
            "AI safety vs AI capabilities — the tension",
            "Emergent behavior in large models",
            "What a tokenizer actually does",
            "Why next-token prediction can produce reasoning",
            "How prompt engineering shapes model output",
            "What chain-of-thought prompting reveals",
            "Why temperature controls randomness in output",
            "How fine-tuning differs from prompting",
            "What a system prompt actually does",
            "Why guardrails aren't the same as alignment",
            "How multi-agent systems divide labor",
            "What tool use actually adds to an LLM",
            "Why grounding reduces hallucination",
            "How vector databases power semantic search",
            "What an embedding space actually represents",
            "Why bigger models aren't always better",
            "How mixture-of-experts models save compute",
            "What model distillation compresses",
            "Why open weights vs closed weights is contested",
            "How red-teaming stress-tests AI systems",
            "What a jailbreak actually exploits",
            "Why constitutional AI tries to self-correct",
            "How AI benchmarks can be gamed",
            "What catastrophic forgetting means",
            "Why scaling laws predict model performance",
            "How synthetic training data changes model behavior",
            "What multimodal models actually combine",
            "Why agentic loops can go wrong",
            "How memory differs from context in AI systems",
            "What a reward model actually scores",
            "Why interpretability research matters for trust",
            "How watermarking AI content works",
            "What the 'stochastic parrot' argument claims",
            "Why AI-generated code still needs review",
            "How model evaluation differs from human evaluation",
            "What a foundation model actually is",
            "Why compute, data, and algorithms all matter",
            "How AI copyright questions actually work",
            "What 'alignment tax' means",
            "Why deceptive alignment is a real concern",
            "How synthetic voices and deepfakes are made",
            "What differentiates narrow AI from AGI",
            "Why AI regulation debates split along risk vs innovation",
        ],
    },
    {
        "name": "Philosophy",
        "topics": [
            "The trolley problem and what it reveals",
            "Free will vs determinism",
            "What makes something morally wrong?",
            "The ship of Theseus and personal identity",
            "Plato's cave allegory",
            "Is consciousness just computation?",
            "Utilitarianism vs deontology — key difference",
            "The problem of induction",
            "What Nietzsche meant by 'God is dead'",
            "Can we ever truly know anything?",
            "What Descartes meant by 'I think, therefore I am'",
            "Why the Chinese Room argument challenges AI",
            "What the veil of ignorance is for",
            "How Kant's categorical imperative actually works",
            "Why the is-ought problem still matters",
            "What existentialism actually claims about meaning",
            "How the paradox of the heap challenges logic",
            "Why Zeno's paradoxes still puzzle us",
            "What social contract theory argues",
            "How virtue ethics differs from rule-based ethics",
            "Why Occam's razor favors simple explanations",
            "What solipsism actually claims",
            "How the problem of evil challenges theism",
            "Why moral relativism is controversial",
            "What the experience machine thought experiment shows",
            "How compatibilism reconciles free will and determinism",
            "Why Sartre said 'existence precedes essence'",
            "What the paradox of tolerance argues",
            "How the Ship of Theseus applies to identity over time",
            "Why Camus called life 'absurd'",
            "What panpsychism claims about consciousness",
            "How the hard problem of consciousness differs from the easy problems",
            "Why Hume was skeptical of causation",
            "What the Gettier problem does to the definition of knowledge",
            "How nihilism differs from existentialism",
            "Why Wittgenstein said language shapes thought",
            "What the paradox of hedonism reveals",
            "How stoicism defines the good life",
            "Why Rawls argued for justice as fairness",
            "What the repugnant conclusion is in ethics",
            "How determinism challenges moral responsibility",
            "Why the ethics of care differs from traditional ethics",
            "What Plato's theory of forms claims",
            "How Aristotle defined eudaimonia",
            "Why the paradox of free will and omniscience persists",
            "What moral luck reveals about blame",
            "How pragmatism defines truth",
            "Why the trolley problem has so many variants",
            "What personal identity means over time",
            "How the meaning of life question resists a single answer",
        ],
    },
    {
        "name": "Economics",
        "topics": [
            "Why inflation happens",
            "Supply and demand — the core insight",
            "What GDP actually measures (and misses)",
            "How central banks control interest rates",
            "Game theory in everyday decisions",
            "The prisoner's dilemma explained",
            "Why comparative advantage drives trade",
            "What a recession technically is",
            "Behavioral economics: people aren't rational",
            "The gig economy and what it changes",
            "Why opportunity cost is the core economic idea",
            "How elasticity measures consumer sensitivity to price",
            "What a market failure actually is",
            "Why externalities need government intervention",
            "How monopolies distort efficient markets",
            "What deadweight loss actually represents",
            "Why public goods are underprovided by markets",
            "How the tragedy of the commons plays out",
            "What fiscal policy vs monetary policy means",
            "Why quantitative easing is controversial",
            "How exchange rates are actually determined",
            "What purchasing power parity measures",
            "Why trade deficits aren't inherently bad",
            "How tariffs affect consumers and producers",
            "What the Laffer curve claims about tax rates",
            "Why minimum wage debates are so contested",
            "How income inequality is actually measured",
            "What the Gini coefficient tells you",
            "Why productivity growth drives long-run wages",
            "How the labor market clears (in theory)",
            "What sticky wages explain about unemployment",
            "Why stagflation broke old economic models",
            "How asset bubbles form and burst",
            "What moral hazard means in finance",
            "Why the 2008 crisis was a banking crisis",
            "How diversification reduces investment risk",
            "What compound interest actually does over time",
            "Why efficient market hypothesis is debated",
            "How network effects create winner-take-all markets",
            "What price discrimination actually is",
            "Why price ceilings cause shortages",
            "How subsidies distort market outcomes",
            "What Nash equilibrium means in practice",
            "Why auctions are designed the way they are",
            "How cryptocurrency challenges monetary theory",
            "What universal basic income proposes to fix",
            "Why automation anxiety echoes past technology fears",
            "How globalization reshaped labor markets",
            "What crowding out means in public spending",
            "Why economic growth and wellbeing aren't the same thing",
        ],
    },
    {
        "name": "Psychology",
        "topics": [
            "Cognitive dissonance and how we resolve it",
            "The Dunning-Kruger effect explained",
            "Why habits form and how to change them",
            "The psychology of loss aversion",
            "Confirmation bias in everyday thinking",
            "What flow state actually is",
            "Intrinsic vs extrinsic motivation",
            "How sleep affects memory consolidation",
            "The bystander effect and diffusion of responsibility",
            "Why stress impairs decision-making",
            "What the placebo effect reveals about the mind",
            "How classical conditioning actually works",
            "Why operant conditioning shapes behavior",
            "What the availability heuristic distorts",
            "How anchoring bias skews our judgments",
            "Why the halo effect changes first impressions",
            "What imposter syndrome actually is",
            "How attachment styles form in childhood",
            "Why the Stanford prison experiment is still debated",
            "What Milgram's obedience study revealed",
            "How groupthink leads to bad decisions",
            "Why the mere exposure effect makes us like familiar things",
            "What the spotlight effect gets wrong",
            "How self-fulfilling prophecies actually work",
            "Why the paradox of choice can reduce happiness",
            "What the Zeigarnik effect explains about unfinished tasks",
            "How emotional regulation actually works",
            "Why rumination worsens depression",
            "What cognitive behavioral therapy targets",
            "How mindfulness changes brain activity",
            "Why nostalgia serves a psychological function",
            "What the peak-end rule reveals about memory",
            "How false memories can be implanted",
            "Why eyewitness testimony is often unreliable",
            "What the Big Five personality traits measure",
            "How nature vs nurture debates evolved",
            "Why resilience can be built, not just innate",
            "What learned helplessness actually is",
            "How social comparison shapes self-esteem",
            "Why procrastination is an emotion regulation problem",
            "What the sunk cost fallacy does to decisions",
            "How framing effects change choices",
            "Why multitasking actually hurts performance",
            "What emotional intelligence actually measures",
            "How trauma reshapes the nervous system",
            "Why grief doesn't follow neat stages",
            "What the psychology of persuasion relies on",
            "How implicit bias differs from explicit bias",
            "Why humor is a coping mechanism",
            "What positive psychology focuses on that traditional psychology didn't",
        ],
    },
    {
        "name": "Neuroscience",
        "topics": [
            "How neurons communicate",
            "What dopamine actually does (it's not just pleasure)",
            "The difference between short and long-term memory",
            "Neuroplasticity — what it means and what it doesn't",
            "Why we dream",
            "How fear is processed in the brain",
            "The role of the prefrontal cortex",
            "What happens in the brain during meditation",
            "Why chronic stress physically changes the brain",
            "What an action potential actually is",
            "How synapses strengthen with use",
            "Why myelin speeds up nerve signals",
            "What the blood-brain barrier protects against",
            "How the hippocampus forms new memories",
            "Why the amygdala is central to emotion",
            "What mirror neurons might actually do",
            "How the brain's reward circuit works",
            "Why serotonin isn't just a 'happiness chemical'",
            "What glial cells do besides support neurons",
            "How the brain filters sensory information",
            "Why phantom limb pain happens",
            "What split-brain studies revealed",
            "How language is processed across brain regions",
            "Why left-brain/right-brain is mostly a myth",
            "What brain plasticity looks like after injury",
            "How circadian rhythms are controlled in the brain",
            "Why sleep deprivation impairs cognition",
            "What REM sleep does for the brain",
            "How addiction hijacks the reward system",
            "Why the brain consumes so much energy",
            "What an EEG actually measures",
            "How fMRI infers brain activity",
            "Why the default mode network matters",
            "What happens in the brain during anesthesia",
            "How pain signals travel to the brain",
            "Why placebo effects have measurable brain correlates",
            "What neurodegeneration actually looks like",
            "How Alzheimer's disease affects the brain",
            "Why Parkinson's involves dopamine neuron loss",
            "What a stroke does to brain tissue",
            "How the brain recovers (or doesn't) after damage",
            "Why some memories fade and others don't",
            "What working memory capacity actually limits",
            "How attention is filtered at the neural level",
            "Why multitasking overloads the prefrontal cortex",
            "What consciousness researchers actually study",
            "How anesthesia turns off awareness",
            "Why the brain has a 'use it or lose it' principle",
            "What neurogenesis means in the adult brain",
            "How exercise physically changes brain structure",
        ],
    },
    {
        "name": "Physics",
        "topics": [
            "Why nothing can travel faster than light",
            "What entropy actually means",
            "How quantum superposition works",
            "The double-slit experiment explained",
            "Why time slows down at high speeds",
            "What a black hole event horizon is",
            "The difference between mass and weight",
            "How nuclear fission releases energy",
            "Dark matter — what we know and don't know",
            "Why the sky is blue",
            "What quantum entanglement actually is",
            "Why Schrödinger's cat is a thought experiment, not a claim",
            "How the uncertainty principle limits measurement",
            "What wave-particle duality actually means",
            "Why E=mc² connects mass and energy",
            "How gravity bends spacetime",
            "What gravitational waves actually are",
            "Why the speed of light is a universal constant",
            "How nuclear fusion powers the sun",
            "What antimatter actually is",
            "Why the Higgs boson matters",
            "How particle accelerators actually work",
            "What the strong and weak nuclear forces do",
            "Why symmetry matters in physics",
            "How superconductors work",
            "What absolute zero actually means",
            "Why perpetual motion machines are impossible",
            "How lasers produce coherent light",
            "What the Big Bang theory actually claims",
            "How the universe's expansion is measured",
            "Why dark energy is even stranger than dark matter",
            "What redshift tells astronomers",
            "How black holes eventually evaporate (Hawking radiation)",
            "Why time is relative, not absolute",
            "What a reference frame means in relativity",
            "How GPS satellites correct for relativity",
            "Why chaos theory makes weather hard to predict",
            "What the butterfly effect actually describes",
            "How friction converts motion into heat",
            "Why objects in orbit are actually falling",
            "What escape velocity actually means",
            "How Newton's third law explains rocket propulsion",
            "Why quantum computers exploit superposition",
            "What decoherence does to quantum states",
            "How the photoelectric effect proved light is quantized",
            "Why the standard model is physics' best current theory",
            "What string theory attempts to unify",
            "How thermodynamics' second law limits efficiency",
            "Why entropy's steady increase defines time's arrow",
            "What a Bose-Einstein condensate actually is",
        ],
    },
    {
        "name": "Climate & Environment",
        "topics": [
            "How the greenhouse effect works",
            "Why carbon dioxide is the main focus",
            "Ocean acidification explained",
            "The difference between weather and climate",
            "How deforestation affects rainfall patterns",
            "What tipping points mean in climate science",
            "Why biodiversity loss matters for humans",
            "How carbon capture works",
            "The water cycle and why it's changing",
            "What net zero actually means",
            "Why methane is a bigger short-term problem than CO2",
            "How ice cores reveal Earth's climate history",
            "What a carbon sink actually does",
            "Why permafrost thaw could accelerate warming",
            "How rising sea levels are actually measured",
            "What coral bleaching reveals about ocean health",
            "Why the Amazon is called both a carbon sink and a carbon risk",
            "How renewable energy differs in reliability from fossil fuels",
            "What a carbon tax actually does",
            "Why cap-and-trade systems work (or don't)",
            "How solar panels convert sunlight to electricity",
            "What makes wind power intermittent",
            "Why nuclear power remains controversial in climate policy",
            "How electric vehicles compare on lifecycle emissions",
            "What the IPCC actually does",
            "Why 1.5°C became the global target",
            "How climate models make predictions",
            "What climate feedback loops actually are",
            "Why extreme weather is linked to climate change",
            "How droughts and floods can both worsen with warming",
            "What ocean currents like the Gulf Stream regulate",
            "Why melting glaciers threaten freshwater supplies",
            "How urban heat islands form",
            "What sustainable agriculture actually changes",
            "Why food waste is a climate issue",
            "How overfishing collapses ocean ecosystems",
            "What a circular economy actually means",
            "Why fast fashion has a large carbon footprint",
            "How carbon offsets are supposed to work",
            "Why greenwashing undermines climate progress",
            "What climate justice actually argues",
            "How climate migration is already happening",
            "Why small island nations are most at risk",
            "How reforestation differs from afforestation",
            "What rewilding actually attempts to restore",
            "Why plastic pollution and climate change are linked",
            "How air pollution and climate change share causes",
            "What a just transition means for fossil fuel workers",
            "Why individual action and systemic change both matter",
            "How climate tipping points could cascade into each other",
        ],
    },
    {
        "name": "History",
        "topics": [
            "Why the Roman Empire fell",
            "The causes of World War I",
            "How the Cold War shaped the modern world",
            "The Industrial Revolution's real impact",
            "Why the printing press changed everything",
            "The origins of democracy in Athens",
            "How colonialism still shapes geopolitics",
            "The significance of the Magna Carta",
            "What caused the Great Depression",
            "How the internet changed power structures",
            "Why the fall of Constantinople reshaped trade routes",
            "How the Black Death changed European society",
            "What the Renaissance actually revived",
            "Why the Protestant Reformation split Europe",
            "How the Silk Road connected ancient economies",
            "What the Age of Exploration actually unleashed",
            "Why the French Revolution turned violent",
            "How Napoleon reshaped European borders",
            "What the Congress of Vienna tried to prevent",
            "Why the American Revolution succeeded where others failed",
            "How the transatlantic slave trade shaped three continents",
            "What abolition actually took to achieve",
            "Why the US Civil War was fundamentally about slavery",
            "How the scramble for Africa was decided by outsiders",
            "What triggered the Russian Revolution",
            "Why World War II's causes trace back to WWI's aftermath",
            "How the Holocaust was allowed to happen",
            "What the Manhattan Project actually changed",
            "Why the atomic bombings remain morally contested",
            "How the United Nations was meant to prevent another world war",
            "What decolonization looked like across Africa and Asia",
            "Why the Cuban Missile Crisis nearly went nuclear",
            "How the civil rights movement changed American law",
            "What the fall of the Berlin Wall actually meant",
            "Why the Soviet Union collapsed when it did",
            "How the Cultural Revolution reshaped China",
            "What the Iranian Revolution changed in the Middle East",
            "Why apartheid ended when it did in South Africa",
            "How the Rwandan genocide unfolded so quickly",
            "What the Marshall Plan actually rebuilt",
            "Why the gold standard was eventually abandoned",
            "How the printing press enabled the Reformation",
            "What the Enlightenment actually argued for",
            "Why the Ottoman Empire's collapse still shapes the Middle East",
            "How the partition of India led to mass displacement",
            "What the Vietnam War changed about American foreign policy",
            "Why the Space Race was really a Cold War proxy",
            "How trade empires like the British East India Company operated",
            "What the Treaty of Versailles got wrong",
            "Why history keeps returning to the same power struggles",
        ],
    },
    {
        "name": "Geopolitics",
        "topics": [
            "Why geography shapes national strategy",
            "What NATO is and why it exists",
            "The US-China rivalry explained",
            "Why the Middle East is geopolitically significant",
            "How sanctions actually work",
            "What soft power is and why it matters",
            "The Belt and Road Initiative",
            "Why small nations punch above their weight",
            "How nuclear deterrence works",
            "What drives resource conflicts",
            "Why the UN Security Council veto shapes global politics",
            "How the EU balances sovereignty and integration",
            "What Brexit actually changed for the UK and EU",
            "Why Taiwan is a geopolitical flashpoint",
            "How the South China Sea disputes actually work",
            "What the Indo-Pacific strategy is responding to",
            "Why the Arctic is becoming geopolitically important",
            "How energy dependence shapes foreign policy",
            "What OPEC actually controls",
            "Why the petrodollar system matters",
            "How currency wars actually play out",
            "What proxy wars accomplish for great powers",
            "Why alliances like NATO create both security and risk",
            "How buffer states shape regional stability",
            "What the 'great game' historically referred to",
            "How Russia's actions in Ukraine reshaped European security",
            "Why economic interdependence can deter or enable conflict",
            "What a sphere of influence actually means today",
            "Why refugee flows become geopolitical leverage",
            "How cyber warfare changes the rules of conflict",
            "What critical mineral supply chains reveal about power",
            "Why semiconductor manufacturing became a geopolitical chokepoint",
            "How space is becoming a new geopolitical frontier",
            "What 'multipolarity' means for global order",
            "Why the Global South is asserting more influence",
            "How international law is enforced (or isn't)",
            "What the International Criminal Court can and can't do",
            "Why humanitarian intervention is so contested",
            "How trade agreements double as strategic alliances",
            "What decoupling means in US-China economic relations",
            "Why chip export controls became a geopolitical weapon",
            "How diaspora communities influence foreign policy",
            "What 'strategic ambiguity' means for Taiwan policy",
            "Why water scarcity is becoming a security issue",
            "How failed states create regional instability",
            "What peacekeeping missions actually accomplish",
            "Why terrorism strategies shifted after 9/11",
            "How economic sanctions affect ordinary citizens",
            "What 'great power competition' means today",
            "Why history and geography still predict conflict better than ideology",
        ],
    },
    {
        "name": "Entrepreneurship",
        "topics": [
            "Product-market fit — how to know when you have it",
            "Why most startups fail",
            "The difference between a vision and a strategy",
            "How venture capital actually works",
            "Why distribution beats product in the early days",
            "What a moat is in business",
            "The lean startup methodology",
            "Why pricing is a positioning decision",
            "How to think about burn rate",
            "Why the second founder problem is real",
            "What a minimum viable product actually tests",
            "Why founders should talk to customers before building",
            "How a cap table actually works",
            "What dilution means for founders over time",
            "Why a term sheet is more than just a valuation",
            "How convertible notes and SAFEs differ",
            "What a Series A investor actually looks for",
            "Why runway determines startup decisions",
            "How to think about customer acquisition cost",
            "What lifetime value actually measures",
            "Why churn quietly kills SaaS businesses",
            "How network effects create defensible businesses",
            "What a flywheel actually describes",
            "Why 'growth hacking' is mostly just good marketing",
            "How founders should think about co-founder equity splits",
            "What vesting schedules protect against",
            "Why a pivot isn't the same as giving up",
            "How to validate an idea before quitting your job",
            "What bootstrapping trades off against raising capital",
            "Why some businesses shouldn't take venture capital",
            "How a board of directors actually functions",
            "What founder-market fit means",
            "Why storytelling matters in fundraising",
            "How to think about competitive moats beyond product",
            "What 'blitzscaling' actually risks",
            "Why unit economics matter more than growth alone",
            "How marketplaces solve the chicken-and-egg problem",
            "What a beachhead market strategy is",
            "Why timing is often the real reason startups win or lose",
            "How acquihires actually work",
            "What due diligence actually checks for",
            "Why startup culture is set in the first ten hires",
            "How to think about hiring before you're ready",
            "What a fiduciary duty means for founders",
            "Why down rounds happen and what they signal",
            "How exits actually happen — IPO vs acquisition",
            "What 'founder mode' means as a management style",
            "Why some ideas are too early rather than wrong",
            "How to think about competition as validation",
            "Why most advice about startups is survivorship bias",
        ],
    },
    {
        "name": "Mathematics",
        "topics": [
            "Why division by zero is undefined",
            "What infinity means in mathematics",
            "The beauty of prime numbers",
            "How Bayes' theorem changes how you think",
            "What a proof actually is",
            "Why 0.999... equals 1",
            "The Monty Hall problem explained",
            "What topology studies",
            "How RSA encryption relies on number theory",
            "The birthday paradox and probability intuition",
            "Why pi is irrational",
            "What imaginary numbers actually represent",
            "How Euler's identity connects five constants",
            "Why the Fibonacci sequence shows up in nature",
            "What the golden ratio actually is",
            "How calculus describes change",
            "What a derivative actually measures",
            "Why integrals compute area under a curve",
            "What a limit formally means",
            "How the Pythagorean theorem was actually proved",
            "Why Fermat's Last Theorem took 350 years to solve",
            "What Gödel's incompleteness theorems actually show",
            "How set theory underlies modern mathematics",
            "What a function actually is, formally",
            "Why matrix multiplication isn't commutative",
            "How eigenvalues reveal a matrix's behavior",
            "What linear independence actually means",
            "Why the central limit theorem is so powerful",
            "How standard deviation measures spread",
            "What correlation does and doesn't tell you",
            "Why p-values are widely misunderstood",
            "How probability differs from statistics",
            "What a Markov chain actually models",
            "Why combinatorics counts without listing everything",
            "How graph theory models networks",
            "What the traveling salesman problem asks",
            "Why NP-complete problems are so hard",
            "How modular arithmetic works",
            "What makes a number 'perfect' in number theory",
            "Why mathematicians care about proof by induction",
            "How the four-color theorem was finally proved",
            "What non-Euclidean geometry challenges",
            "Why fractals have infinite detail",
            "How chaos theory relates to deterministic systems",
            "What game theory's minimax theorem proves",
            "Why the halting problem is unsolvable",
            "How cryptographic hash functions use math",
            "What makes a proof 'elegant' to mathematicians",
            "Why zero was a genuinely radical invention",
            "How mathematics describes things that don't physically exist",
        ],
    },
    {
        "name": "Biology",
        "topics": [
            "How DNA replication works",
            "Why evolution is a theory (in the scientific sense)",
            "What CRISPR actually does",
            "How vaccines train the immune system",
            "The difference between viruses and bacteria",
            "Why cells divide — and why they stop",
            "How natural selection differs from random mutation",
            "What mitochondria actually do",
            "The gut microbiome and why it matters",
            "How antibiotic resistance develops",
            "What a gene actually is, physically",
            "How proteins are built from DNA instructions",
            "Why RNA plays more roles than just a DNA messenger",
            "What epigenetics actually changes (not the DNA itself)",
            "How mutations create genetic diversity",
            "Why most mutations are neutral, not harmful",
            "What speciation actually requires",
            "How convergent evolution produces similar traits independently",
            "Why the peppered moth is a classic evolution example",
            "What homologous structures reveal about common ancestry",
            "How vestigial structures hint at evolutionary history",
            "Why the human appendix isn't fully understood",
            "What symbiosis actually means in ecosystems",
            "How photosynthesis converts light into energy",
            "Why the Krebs cycle is central to cellular respiration",
            "What ATP actually powers in a cell",
            "How enzymes speed up biological reactions",
            "Why protein folding determines function",
            "What a stem cell can and can't become",
            "How organ transplants trigger immune rejection",
            "Why blood types matter for transfusions",
            "What the lymphatic system actually does",
            "How the immune system tells self from non-self",
            "Why autoimmune diseases attack the body's own cells",
            "What allergies actually are, immunologically",
            "How cancer cells evade the immune system",
            "Why tumor suppressor genes matter",
            "What metastasis actually involves",
            "How chemotherapy targets dividing cells",
            "Why biodiversity stabilizes ecosystems",
            "What a keystone species actually does",
            "How invasive species disrupt ecosystems",
            "Why extinction rates are accelerating",
            "What a food web reveals that a food chain hides",
            "How coral reefs support disproportionate biodiversity",
            "Why bacteria can share DNA with each other",
            "What makes viruses not quite 'alive'",
            "How pandemics emerge from animal reservoirs",
            "Why herd immunity thresholds vary by disease",
            "What longevity research has learned from cellular aging",
        ],
    },
]


async def seed_areas(db):
    existing_areas = await db.execute(select(Area).where(Area.name.in_(a["name"] for a in SEED_DATA)))
    areas_by_name = {a.name: a for a in existing_areas.scalars().all()}

    for area_data in SEED_DATA:
        area = areas_by_name.get(area_data["name"])
        if not area:
            area = Area(name=area_data["name"])
            db.add(area)
            await db.flush()
            areas_by_name[area_data["name"]] = area

    await db.flush()

    all_area_ids = [a.id for a in areas_by_name.values()]
    existing_topics = await db.execute(
        select(Topic.area_id, Topic.name).where(Topic.area_id.in_(all_area_ids))
    )
    existing_pairs = {(area_id, name) for area_id, name in existing_topics.all()}

    for area_data in SEED_DATA:
        area = areas_by_name[area_data["name"]]
        for topic_name in area_data["topics"]:
            if (area.id, topic_name) not in existing_pairs:
                db.add(Topic(name=topic_name, area_id=area.id))

    await db.commit()
    print("Seeded global areas and topics.")


async def seed_dev_user(db):
    existing = await db.execute(select(User).where(User.email == SEED_EMAIL))
    if existing.scalar_one_or_none():
        print(f"Dev user {SEED_EMAIL} already exists, skipping.")
        return

    seed_password = secrets.token_urlsafe(24)
    user = User(email=SEED_EMAIL, password=hash_password(seed_password))
    db.add(user)
    await db.flush()

    areas_result = await db.execute(select(Area))
    for area in areas_result.scalars().all():
        db.add(UserArea(user_id=user.id, area_id=area.id))

    await db.commit()
    print(f"Seeded dev user: {SEED_EMAIL} / {seed_password}")


async def seed():
    engine = create_async_engine(settings.database_url, connect_args={"statement_cache_size": 0}, echo=False)
    SessionLocal = async_sessionmaker(engine, expire_on_commit=False)

    async with SessionLocal() as db:
        await seed_areas(db)
        if settings.environment != "production":
            await seed_dev_user(db)

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
