"""add user_id to areas for custom areas

Revision ID: 6c38b1fcf8ff
Revises: fc7d713244a1
Create Date: 2026-05-31 17:03:04.410483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c38b1fcf8ff'
down_revision: Union[str, None] = 'fc7d713244a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('areas_name_key'), 'areas', type_='unique')
    op.create_unique_constraint(None, 'areas', ['name', 'user_id'])
    op.create_foreign_key(None, 'areas', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_constraint(None, 'areas', type_='unique')
    op.create_unique_constraint(op.f('areas_name_key'), 'areas', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('areas', 'user_id')
    # ### end Alembic commands ###
