"""drop type from areas

Revision ID: fc7d713244a1
Revises: fe5cc3a8e112
Create Date: 2026-05-31 16:58:55.172836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc7d713244a1'
down_revision: Union[str, None] = 'fe5cc3a8e112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('type', postgresql.ENUM('KNOWN', 'NEW', name='areatype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
