"""remove user_id from areas, add user_areas

Revision ID: fe5cc3a8e112
Revises: 0001_initial
Create Date: 2026-05-31 16:53:12.702300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5cc3a8e112'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'area_id')
    )
    op.drop_constraint(op.f('areas_name_user_id_key'), 'areas', type_='unique')
    op.create_unique_constraint(None, 'areas', ['name'])
    op.drop_constraint(op.f('areas_user_id_fkey'), 'areas', type_='foreignkey')
    op.drop_column('areas', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('areas_user_id_fkey'), 'areas', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'areas', type_='unique')
    op.create_unique_constraint(op.f('areas_name_user_id_key'), 'areas', ['name', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('user_areas')
    # ### end Alembic commands ###
